// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4ZQW9FCSq3LB3oxuDJwBcVYCivE3cDJA',
    appId: '1:157337589469:web:68b5168f9f7cd2e85aed34',
    messagingSenderId: '157337589469',
    projectId: 'geo-fencing-8970a',
    authDomain: 'geo-fencing-8970a.firebaseapp.com',
    storageBucket: 'geo-fencing-8970a.firebasestorage.app',
    measurementId: 'G-HCLV96RL15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXp9qwn4_C3NISrl0N8oCsimFQzOsJE_0',
    appId: '1:157337589469:android:ded1509f728f09175aed34',
    messagingSenderId: '157337589469',
    projectId: 'geo-fencing-8970a',
    storageBucket: 'geo-fencing-8970a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDddb3CIkt-AwyJv93XnczEDS-kdm1YCb8',
    appId: '1:157337589469:ios:a931ba0fea70901d5aed34',
    messagingSenderId: '157337589469',
    projectId: 'geo-fencing-8970a',
    storageBucket: 'geo-fencing-8970a.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDddb3CIkt-AwyJv93XnczEDS-kdm1YCb8',
    appId: '1:157337589469:ios:a931ba0fea70901d5aed34',
    messagingSenderId: '157337589469',
    projectId: 'geo-fencing-8970a',
    storageBucket: 'geo-fencing-8970a.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4ZQW9FCSq3LB3oxuDJwBcVYCivE3cDJA',
    appId: '1:157337589469:web:71fa624fd07239cb5aed34',
    messagingSenderId: '157337589469',
    projectId: 'geo-fencing-8970a',
    authDomain: 'geo-fencing-8970a.firebaseapp.com',
    storageBucket: 'geo-fencing-8970a.firebasestorage.app',
    measurementId: 'G-3TZ1QVFPJ8',
  );
}
